# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
"""
Bake TrueType fonts into C++ bitmap-font headers for the tide display.

The ESP32 can't open a .ttf, so each font is pre-rendered here, once, at
the exact pixel size the layout uses. Output: tide_standalone/fonts.h,
one struct per size, 1 bit per pixel.

    uv run tools/make_fonts.py            # needs DejaVu Sans; see FONT_DIR

DejaVu Sans is matplotlib's default font, so the chart looks like the
Python version. Its license (Bitstream Vera) allows embedding.

To add a size: add a line to FONTS and re-run. The header is regenerated
from scratch -- never edit it by hand.
"""
import sys
from pathlib import Path

from PIL import ImageFont

# Where DejaVu lives. Linux: here. Mac: `brew install --cask font-dejavu`,
# then ~/Library/Fonts. Only needed to regenerate fonts.h -- which is
# committed, so normal builds never run this script.
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
REGULAR = "DejaVuSans.ttf"
BOLD = "DejaVuSans-Bold.ttf"

# (C name, file, pixel size). Pixel size = matplotlib points * 100/72,
# because the Python version renders at 100 dpi.
FONTS = [
    ("font_tiny",     REGULAR, 13),   #  9 pt  footer, captions
    ("font_small",    REGULAR, 14),   # 10 pt  tick labels, peak labels
    ("font_small_b",  BOLD,    14),   # 10 pt  LAST / NEXT headers
    ("font_body",     REGULAR, 17),   # 12 pt  event lines
    ("font_state",    REGULAR, 15),   # 11 pt  "falling"
    ("font_state_b",  BOLD,    15),   # 11 pt  offset line
    ("font_title",    BOLD,    26),   # 19 pt  station name
    ("font_headline", BOLD,    36),   # 26 pt  current height
]

# Printable ASCII plus the few specials the layout uses.
CHARS = [chr(c) for c in range(32, 127)] + [
    "↑", "↓",   # up/down arrows
    "·",             # middle dot
    "−",             # real minus sign, for axis labels
    "°",             # degree sign, for later
]
CHARS.sort(key=ord)   # the lookup in canvas.cpp is a binary search
THRESHOLD = 110   # 0-255; lower = bolder strokes after antialiasing is dropped


def bake(name, path, size):
    font = ImageFont.truetype(str(path), size)
    ascent, descent = font.getmetrics()
    glyphs, bitmap = [], bytearray()
    for ch in CHARS:
        adv = round(font.getlength(ch))
        mask, (ox, oy) = font.getmask2(ch, mode="L", anchor="ls")
        w, h = mask.size
        if w == 0 or h == 0 or ch == " ":
            glyphs.append((ord(ch), len(bitmap), 0, 0, 0, 0, adv))
            continue
        offset = len(bitmap)
        bits, nbits = 0, 0
        for y in range(h):
            for x in range(w):
                bits = (bits << 1) | (1 if mask.getpixel((x, y)) >= THRESHOLD else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(bits); bits = nbits = 0
        if nbits:
            bitmap.append(bits << (8 - nbits))
        glyphs.append((ord(ch), offset, w, h, ox, oy, adv))
    return ascent, descent, glyphs, bitmap


def main():
    out = Path(__file__).resolve().parent.parent / "tide_standalone" / "fonts.h"
    lines = [
        "// GENERATED by tools/make_fonts.py -- do not edit by hand.",
        "// DejaVu Sans (Bitstream Vera license). 1 bit per pixel, rows",
        "// packed MSB-first and continuous across row ends.",
        "#pragma once",
        '#include "font.h"',
        "",
    ]
    total = 0
    for name, file, size in FONTS:
        ascent, descent, glyphs, bitmap = bake(name, FONT_DIR / file, size)
        total += len(bitmap) + len(glyphs) * 12
        lines.append(f"// {file} @ {size}px")
        lines.append(f"static const uint8_t {name}_bits[] = {{")
        for i in range(0, len(bitmap), 20):
            lines.append("  " + ",".join(f"0x{b:02x}" for b in bitmap[i:i + 20]) + ",")
        lines.append("};")
        lines.append(f"static const Glyph {name}_glyphs[] = {{")
        for cp, off, w, h, ox, oy, adv in glyphs:
            lines.append(f"  {{0x{cp:04x},{off},{w},{h},{ox},{oy},{adv}}},")
        lines.append("};")
        lines.append(f"static const Font {name} = {{ {name}_bits, {name}_glyphs, "
                     f"{len(glyphs)}, {ascent}, {descent} }};")
        lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out}  ({total / 1024:.1f} KB of font data)")


if __name__ == "__main__":
    sys.exit(main())
