# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
"""
Bake TrueType fonts into C++ bitmap-font headers for the tide display.

The ESP32 can't open a .ttf, so each font is pre-rendered here, once, at
the exact pixel size the layout uses. Output: tide_standalone/fonts.h,
one struct per size, 1 bit per pixel.

    uv run tools/make_fonts.py            # needs DejaVu Sans; see FONT_DIR

DejaVu Sans is matplotlib's default font, so the chart looks like the
Python version. Its license (Bitstream Vera) allows embedding.

To add a size: add a line to FONTS and re-run. The header is regenerated
from scratch -- never edit it by hand.
"""
import sys
from pathlib import Path

from PIL import ImageFont

# Where DejaVu lives. Linux: here. Mac: `brew install --cask font-dejavu`,
# then ~/Library/Fonts. Only needed to regenerate fonts.h -- which is
# committed, so normal builds never run this script.
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
REGULAR = "DejaVuSans.ttf"
BOLD = "DejaVuSans-Bold.ttf"

# (C name, file, pixel size). Pixel size = matplotlib points * 100/72,
# because the Python version renders at 100 dpi.
FONTS = [
    ("font_tiny",     REGULAR, 13),   #  9 pt  footer, captions
    ("font_small",    REGULAR, 14),   # 10 pt  tick labels, peak labels
    ("font_small_b",  BOLD,    14),   # 10 pt  LAST / NEXT headers
    ("font_body",     REGULAR, 17),   # 12 pt  event lines
    ("font_state",    REGULAR, 15),   # 11 pt  "falling"
    ("font_state_b",  BOLD,    15),   # 11 pt  offset line
    ("font_title",    BOLD,    26),   # 19 pt  station name
    ("font_headline", BOLD,    36),   # 26 pt  current height
]

# Printable ASCII plus the few specials the layout uses.
CHARS = [chr(c) for c in range(32, 127)] + [
    "↑", "↓",   # up/down arrows
    "·",             # middle dot
    "−",             # real minus sign, for axis labels
    "°",             # degree sign, for later
]
CHARS.sort(key=ord)   # the lookup in canvas.cpp is a binary search
THRESHOLD = 110   # 0-255; lower = bolder strokes after antialiasing is dropped


def _pack(mask, bpp, value):
    """Pack a PIL mask into bytes, `bpp` bits per pixel, rows continuous."""
    w, h = mask.size
    out, acc, nbits = bytearray(), 0, 0
    for y in range(h):
        for x in range(w):
            acc = (acc << bpp) | value(mask.getpixel((x, y)))
            nbits += bpp
            if nbits == 8:
                out.append(acc); acc = nbits = 0
    if nbits:
        out.append(acc << (8 - nbits))
    return out


def bake(name, path, size):
    """Two renderings of every glyph:

    mono  1 bit/pixel, FreeType's hinted black-and-white mode -- strokes
          snapped to whole pixels, so small text stays crisp and unbroken
          on a 1-bit panel. (Thresholding the smooth version instead drops
          pixels from thin diagonals: the broken-up M and W.)
    aa    2 bits/pixel of ink coverage (0 none .. 3 full), for panels with
          gray levels, where edge pixels can be drawn in gray.
    """
    font = ImageFont.truetype(str(path), size)
    ascent, descent = font.getmetrics()
    glyphs, bitmap = [], bytearray()
    for ch in CHARS:
        adv = round(font.getlength(ch))
        entry = [ord(ch), adv]
        for mode, bpp, value in (("1", 1, lambda v: 1 if v else 0),
                                 ("L", 2, lambda v: min(3, (v * 3 + 127) // 255))):
            mask, (ox, oy) = font.getmask2(ch, mode=mode, anchor="ls")
            w, h = mask.size
            if ch == " " or w == 0 or h == 0:
                entry += [len(bitmap), 0, 0, 0, 0]
                continue
            entry += [len(bitmap), w, h, ox, oy]
            bitmap += _pack(mask, bpp, value)
        glyphs.append(entry)
    return ascent, descent, glyphs, bitmap


def main():
    out = Path(__file__).resolve().parent.parent / "tide_standalone" / "fonts.h"
    lines = [
        "// GENERATED by tools/make_fonts.py -- do not edit by hand.",
        "// DejaVu Sans (Bitstream Vera license). Each glyph twice: hinted",
        "// 1 bit/pixel, and 2 bits/pixel of antialiased coverage. Rows are",
        "// packed MSB-first and continuous across row ends.",
        "#pragma once",
        '#include "font.h"',
        "",
    ]
    total = 0
    for name, file, size in FONTS:
        ascent, descent, glyphs, bitmap = bake(name, FONT_DIR / file, size)
        total += len(bitmap) + len(glyphs) * 20
        lines.append(f"// {file} @ {size}px")
        lines.append(f"static const uint8_t {name}_bits[] = {{")
        for i in range(0, len(bitmap), 20):
            lines.append("  " + ",".join(f"0x{b:02x}" for b in bitmap[i:i + 20]) + ",")
        lines.append("};")
        lines.append(f"static const Glyph {name}_glyphs[] = {{")
        for g in glyphs:
            cp, adv, *rest = g
            lines.append(f"  {{0x{cp:04x},{adv}," + ",".join(str(v) for v in rest) + "},")
        lines.append("};")
        lines.append(f"static const Font {name} = {{ {name}_bits, {name}_glyphs, "
                     f"{len(glyphs)}, {ascent}, {descent} }};")
        lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out}  ({total / 1024:.1f} KB of font data)")


if __name__ == "__main__":
    sys.exit(main())
